name: MKConnect CI/CD

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write   # 👈 برای ساخت Release لازمه

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build binary
        run: |
          ext=""
          if [ "${{ matrix.os }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
          go build -o gocicd-${{ matrix.os }}-${{ matrix.arch }}$ext main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MKConnect-${{ matrix.os }}-${{ matrix.arch }}
          path: MKConnect-${{ matrix.os }}-${{ matrix.arch }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - name: List downloaded artifacts
        run: ls -lh artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/MKConnect-*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}